### ISSUE TITLE
Team alignment

### ISSUE THREAD

**Issue by filopedraz** [premAI-io/prem-website#10]
I had to remove the advisors. Idk if now the alignment is good.

![CleanShot 2024-03-02 at 14 35 07@2x](https://github.com/premAI-io/prem-website/assets/29598954/92378d82-5f68-4088-8e0b-7f1ad067f393)

**Comment by Riccardo-Zanutta** [comment]
@filopedraz can you give me more feedback on this? Screen resolution, device used, ecc

**Comment by filopedraz** [comment]
16", but if you check the code u will understand immediately. Removing 3 people I made the alignment wrong.
